[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
funmarket_pump = "A2EqnLDYW1WAi8mhR12ncGVvt92G3jisJqCe46YoV7SJ"

[programs.localnet]
funmarket_pump = "A2EqnLDYW1WAi8mhR12ncGVvt92G3jisJqCe46YoV7SJ"

[programs.mainnet]
funmarket_pump = "DADaDENa6gPZjy92BjctBDKGqNBHhqPokpr5uY2UY3uJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/funmarket-deploy-mainnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
